In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# PROBLEM STATEMENT
To build a machine learning model that predicts whether a person earns more than $50K per year based on demographic and employment-related features using the Adult dataset

In [2]:
df = pd.read_csv('adult.csv')
df

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                      ?  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                      ?      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

# EXPLORATORY DATA ANALYSIS

In [67]:
df.head()

age  workclass  education.num  marital.status  occupation  relationship  \
0   90          0              9               6           0             1   
1   82          4              9               6           4             1   
2   66          0             10               6           0             4   
3   54          4              4               0           7             4   
4   41          4             10               5          10             3   

   race  sex  capital.gain  capital.loss  hours.per.week  native.country  \
0     4    0             0          4356              40              39   
1     4    0             0          4356              18              39   
2     2    0             0          4356              40              39   
3     4    0             0          3900              40              39   
4     4    0             0          3900              40              39   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
df.shape

(32561, 15)

In [5]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [7]:
df = df.drop(['education' , 'fnlwgt'] , axis = 1)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
df['workclass'] = le.fit_transform(df['workclass'])
df['marital.status'] = le.fit_transform(df['marital.status'])
df['occupation'] = le.fit_transform(df['occupation'])
df['relationship'] = le.fit_transform(df['relationship'])
df['race'] = le.fit_transform(df['race'])
df['sex'] = le.fit_transform(df['sex'])
df['native.country'] = le.fit_transform(df['native.country'])
df['income'] = le.fit_transform(df['income'])

In [10]:
df.corr()

age  workclass  education.num  marital.status  \
age             1.000000   0.003787       0.036527       -0.266288   
workclass       0.003787   1.000000       0.052085       -0.064731   
education.num   0.036527   0.052085       1.000000       -0.069304   
marital.status -0.266288  -0.064731      -0.069304        1.000000   
occupation     -0.020947   0.254892       0.109697       -0.009654   
relationship   -0.263698  -0.090461      -0.094153        0.185451   
race            0.028718   0.049742       0.031838       -0.068013   
sex             0.088832   0.095981       0.012280       -0.129314   
capital.gain    0.077674   0.033835       0.122630       -0.043393   
capital.loss    0.057775   0.012216       0.079923       -0.034187   
hours.per.week  0.068756   0.138962       0.148123       -0.190519   
native.country -0.001151  -0.007690       0.050840       -0.023819   
income          0.234037   0.051604       0.335154       -0.199307   

                occupation  relationship      race       sex  capital.gain  \
age              -0.020947     -0.263698  0.028718  0.088832      0.077674   
workclass         0.254892     -0.090461  0.049742  0.095981      0.033835   
education.num     0.109697     -0.094153  0.031838  0.012280      0.122630   
marital.status   -0.009654      0.185451 -0.068013 -0.129314     -0.043393   
occupation        1.000000     -0.075607  0.006763  0.080296      0.025505   
relationship     -0.075607      1.000000 -0.116055 -0.582454     -0.057919   
race              0.006763     -0.116055  1.000000  0.087204      0.011145   
sex               0.080296     -0.582454  0.087204  1.000000      0.048480   
capital.gain      0.025505     -0.057919  0.011145  0.048480      1.000000   
capital.loss      0.017987     -0.061062  0.018899  0.045567     -0.031615   
hours.per.week    0.080383     -0.248974  0.041910  0.229309      0.078409   
native.country   -0.012543     -0.005507  0.137852 -0.008119     -0.001982   
income            0.075468     -0.250918  0.071846  0.215980      0.223329   

                capital.loss  hours.per.week  native.country    income  
age                 0.057775        0.068756       -0.001151  0.234037  
workclass           0.012216        0.138962       -0.007690  0.051604  
education.num       0.079923        0.148123        0.050840  0.335154  
marital.status     -0.034187       -0.190519       -0.023819 -0.199307  
occupation          0.017987        0.080383       -0.012543  0.075468  
relationship       -0.061062       -0.248974       -0.005507 -0.250918  
race                0.018899        0.041910        0.137852  0.071846  
sex                 0.045567        0.229309       -0.008119  0.215980  
capital.gain       -0.031615        0.078409       -0.001982  0.223329  
capital.loss        1.000000        0.054256        0.000419  0.150526  
hours.per.week      0.054256        1.000000       -0.002671  0.229689  
native.country      0.000419       -0.002671        1.000000  0.015840  
income              0.150526        0.229689        0.015840  1.000000

In [11]:
df.head()

age  workclass  education.num  marital.status  occupation  relationship  \
0   90          0              9               6           0             1   
1   82          4              9               6           4             1   
2   66          0             10               6           0             4   
3   54          4              4               0           7             4   
4   41          4             10               5          10             3   

   race  sex  capital.gain  capital.loss  hours.per.week  native.country  \
0     4    0             0          4356              40              39   
1     4    0             0          4356              18              39   
2     2    0             0          4356              40              39   
3     4    0             0          3900              40              39   
4     4    0             0          3900              40              39   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

# MODEL BUILDING

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x = df.drop('income' , axis = 1)
y = df['income']

In [14]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=1)

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=1)

param_grid = {
    'n_estimators': [200, 300],
    'max_depth': [20, 30],
    'min_samples_split': [2, 5]
}

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr = LogisticRegression()
lr.fit(x_train , y_train)

LogisticRegression()

In [19]:
lr.score(x_test , y_test)*100 , lr.score(x_train , y_train)*100

(82.94180869031167, 82.4247542997543)

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
dtr =  DecisionTreeClassifier(
    max_depth=7,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=1
)


dtr.fit(x_train , y_train)

DecisionTreeClassifier(max_depth=7, min_samples_leaf=5, min_samples_split=10,
                       random_state=1)

In [22]:
dtr.score(x_test , y_test)*100 , dtr.score(x_train , y_train)*100

(86.22754491017965, 85.74938574938575)

In [23]:
y_pred = dtr.predict(x_test)
y_pred[:5]

array([0, 0, 0, 1, 0])

In [24]:
y_test[:5]

9646     0
709      1
7385     0
16671    0
21932    0
Name: income, dtype: int64

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier(max_depth=10 , max_features=8)
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, max_features=8)

In [27]:
rf.score(x_test , y_test)*100 , rf.score(x_train , y_train)*100

(86.73422385997236, 87.6036547911548)

# MODEL EVALUATION

logistic regreesion

In [28]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report

In [29]:
y_pred = lr.predict(x_test)
y_pred[:5]

array([0, 1, 0, 0, 0])

In [30]:
y_test[:5]

9646     0
709      1
7385     0
16671    0
21932    0
Name: income, dtype: int64

In [31]:
 y_pred_train = lr.predict(x_test)

In [32]:
cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_test, y_pred)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[4657  286]
 [ 825  745]]

Accuracy: 0.8294180869031168

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.94      0.89      4943
           1       0.72      0.47      0.57      1570

    accuracy                           0.83      6513
   macro avg       0.79      0.71      0.73      6513
weighted avg       0.82      0.83      0.82      6513



In [33]:
y_pred_train = lr.predict(x_train)

In [34]:
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[18645  1132]
 [ 3446  2825]]

Accuracy: 0.824247542997543

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.94      0.89     19777
           1       0.71      0.45      0.55      6271

    accuracy                           0.82     26048
   macro avg       0.78      0.70      0.72     26048
weighted avg       0.81      0.82      0.81     26048



Decision Tree

In [35]:
y_pred = dtr.predict(x_test)
y_pred[:5]

array([0, 0, 0, 1, 0])

In [36]:
y_test[:5]

9646     0
709      1
7385     0
16671    0
21932    0
Name: income, dtype: int64

In [37]:
y_pred= dtr.predict(x_test)

In [38]:
cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_test, y_pred)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[4725  218]
 [ 679  891]]

Accuracy: 0.8622754491017964

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.96      0.91      4943
           1       0.80      0.57      0.67      1570

    accuracy                           0.86      6513
   macro avg       0.84      0.76      0.79      6513
weighted avg       0.86      0.86      0.85      6513



In [39]:
y_pred_train = dtr.predict(x_train)

In [40]:
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[18841   936]
 [ 2776  3495]]

Accuracy: 0.8574938574938575

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91     19777
           1       0.79      0.56      0.65      6271

    accuracy                           0.86     26048
   macro avg       0.83      0.75      0.78     26048
weighted avg       0.85      0.86      0.85     26048



Random Forest

In [41]:
y_pred = rf.predict(x_test)
y_pred[:5]

array([0, 1, 0, 1, 0])

In [42]:
y_test[:5]

9646     0
709      1
7385     0
16671    0
21932    0
Name: income, dtype: int64

In [43]:
 y_pred = rf.predict(x_test)

In [44]:
cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_test, y_pred)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[4699  244]
 [ 620  950]]

Accuracy: 0.8673422385997236

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.95      0.92      4943
           1       0.80      0.61      0.69      1570

    accuracy                           0.87      6513
   macro avg       0.84      0.78      0.80      6513
weighted avg       0.86      0.87      0.86      6513



In [45]:
y_pred_train = rf.predict(x_train)

In [46]:
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix:\n", cnf_matrix)
print()

accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy:", accuracy)
print()

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report:\n", clf_report)

Confusion Matrix:
 [[18882   895]
 [ 2334  3937]]

Accuracy: 0.876036547911548

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.95      0.92     19777
           1       0.81      0.63      0.71      6271

    accuracy                           0.88     26048
   macro avg       0.85      0.79      0.82     26048
weighted avg       0.87      0.88      0.87     26048



# CONCLUSION

The income classification problem was solved using multiple machine learning algorithms including Logistic Regression, Decision Tree, and Random Forest on the Adult Dataset.
Among all models, Random Forest achieved the highest accuracy (86-87%), followed closely by Decision Tree (85-86%), while Logistic Regression achieved 80% accuracy.

# MODEL TESTING

In [56]:
new_data = X_test.sample(5, random_state=42)
predictions = rf.predict(new_data)

print(predictions)

[0 0 0 0 0]


* model retraining

In [58]:
print(df.columns)

Index(['age', 'workclass', 'education.num', 'marital.status', 'occupation',
       'relationship', 'race', 'sex', 'capital.gain', 'capital.loss',
       'hours.per.week', 'native.country', 'income'],
      dtype='object')


In [60]:
selected_features = [
    "age",
    "education.num",
    "hours.per.week",
    "capital.gain",
    "capital.loss"
]

X = df[selected_features]
y = df["income"]

In [61]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42)

In [62]:
X = df.drop("income", axis=1)   
y = df["income"]

In [63]:
y_pred = rf.predict(X_test)

In [64]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.861200675571933

Confusion Matrix:
 [[4786  190]
 [ 714  823]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.96      0.91      4976
           1       0.81      0.54      0.65      1537

    accuracy                           0.86      6513
   macro avg       0.84      0.75      0.78      6513
weighted avg       0.86      0.86      0.85      6513



In [65]:
print("\nSample Predictions:\n", predictions)


Sample Predictions:
 [0 0 0 0 0]
